name: "Prova"
items:
  - name : "Acqua"
    id: "1"
    incomingPrice: 50
    publicPrice: 100

defaultPayment: &defaultPayment
  minimumDuration: 30
  costPerHour: 1200

gamingStations:
  - name: "Postazione 1"
    id: "1"
    payment: *defaultPayment
