portNumber: 4000
websiteDir: "D:\\ApplicationEnv\\Projects\\aen\\ui"
#websiteDir: "/Users/boss/Projects/aen/ui"
log_level: "debug"
ui_aspect:
   background_image_folder: "/images/background"
   background_image: "background.webp"
   theme: "dark"
   billiard_room_name: "Billiard Room bla bla"
